# Generated by Django 5.0.1 on 2024-01-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrimeIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=200)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("postcode", models.CharField(max_length=10)),
                ("street_name", models.CharField(max_length=200)),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_code", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("fare_zone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="StationUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_code", models.CharField(max_length=200)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("postcode", models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name="property",
            name="postcode",
            field=models.CharField(max_length=10),
            preserve_default=False,
        ),
    ]
