# Generated by Django 5.0.1 on 2024-02-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_area_userquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='centre_lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='centre_long',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
