# Generated by Django 5.0.1 on 2024-02-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_area_centre_lat_area_centre_long'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('house_type', models.CharField(max_length=200)),
                ('area_sqft', models.FloatField()),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('receptions', models.IntegerField(default=0)),
                ('postcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
    ]
