# Generated by Django 5.0.1 on 2024-03-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleChargingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('postcode', models.CharField(max_length=10)),
                ('borough', models.CharField(max_length=200)),
                ('public_use', models.BooleanField()),
            ],
        ),
    ]
