# Generated by Django 5.0.1 on 2024-03-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_vehiclechargingpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
