# Generated by Django 5.0.1 on 2024-03-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_groceryshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenBlueArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=200)),
                ('area_code', models.CharField(max_length=200)),
                ('borough', models.CharField(max_length=200)),
                ('ward_area_hectares', models.FloatField()),
                ('green_area_hectares', models.FloatField()),
                ('blue_area_hectares', models.FloatField()),
                ('green_and_blue_area_hectare', models.FloatField()),
                ('percent_green', models.FloatField()),
                ('percent_blue', models.FloatField()),
                ('percent_green_and_blue', models.FloatField()),
            ],
        ),
    ]
